function [Ms, Cs, Mx, Es, time1] = heisenberg(model,Lat,J1,J2,J3,D,Sp,L,estep,mstep,Ts,para,kb)
%global model Lat J1 J2 J3 D Sp L estep mstep Ts para kb

Ms = zeros(1, size(Ts,2));
Mx = zeros(1, size(Ts,2));
Es = zeros(1, size(Ts,2));
Cs = zeros(1, size(Ts,2));
const = 0.0;
time1 = 0; time2 = 0; time3 = 0;
newC = zeros(1,3);


bar = waitbar(0,'1','Name','Monte-Carlo');
%% Generate a spheracal(uniform) random initial configuration of theta & phi,
%% And the corresponding Cartisian coordinates (without spin!)
gridS = cat(4,acos(1-2*rand(L,L,L)),2*pi*rand(L,L,L));
gridC = cat(4,sin(gridS(:,:,:,1)) .* cos(gridS(:,:,:,2)), ...
              sin(gridS(:,:,:,1)) .* sin(gridS(:,:,:,2)), ...
              cos(gridS(:,:,:,1))                    );

%% Evolve the system for a fixed number of steps
for t = 1:size(Ts,2)   %change into parfor if parellel
    E0 = 0.0; E1 = 0.0; E2 = 0.0; M0 = 0.0; M1 = 0.0; M2 = 0.0;
    const = 1 / (L^2 * Ts(t) * kb) ;  % factor to be used in specific heat
    %grid = zeros(L);                           % move into parfor if parellel
    %grid(:,:) = initiate(:,:) ;  % deep copy?  % move into parfor if parellel
    %gridS = cat(3,acos(1-2*unifrnd(0,1,L,L)),2*pi*unifrnd(0,1,L,L));
    %gridC = cat(3,sin(gridS(:,:,1)) .* cos(gridS(:,:,2)), ...
    %            sin(gridS(:,:,1)) .* sin(gridS(:,:,2)), ...
    %            cos(gridS(:,:,1))                     );
    str=['Calculating: ',num2str(Ts(t)),'K' , ...
         ' (',num2str(100*t/size(Ts,2)),'%) ', ...
         num2str((size(Ts,2)-t)*time3/60), ' min left'];
    waitbar(t/size(Ts,2),bar,str)
    
    tic
    for i=1:(estep+mstep)
    % Pick a random spin and its touching/testing random direction
    row = randi(L);   % or : linearIndex = randi(numel(grid));
    col = randi(L);   % or : [row, col]  = ind2sub(size(grid), linearIndex);
    pil = randi(L);
    gridTS = zeros(1,1,1,2); 
    gridTC = zeros(1,1,1,3); 
    gridTS(1,1,1,:) = [acos(1-2*rand(1,1,1)),2*pi*rand(1,1,1)];
    gridTC(1,1,1,:) = [sin(gridTS(1)) .* cos(gridTS(2)), ...
                       sin(gridTS(1)) .* sin(gridTS(2)), ...
                       cos(gridTS(1))];
    
    neighbors1=[]; neighbors2=[]; neighbors3=[];
    above1 = mod(row - 1 - 1, size(gridC,1)) + 1;
    below1 = mod(row + 1 - 1, size(gridC,1)) + 1;
    left1  = mod(col - 1 - 1, size(gridC,2)) + 1;
    right1 = mod(col + 1 - 1, size(gridC,2)) + 1;
    top1   = mod(pil - 1 - 1, size(gridC,3)) + 1;
    bot1   = mod(pil + 1 - 1, size(gridC,3)) + 1;

    if Lat == "tVCHH"
        neighbors1 = gridC(   row, right1, top1, :) + ...
                     gridC(below1,    col, top1, :) + ...
                     gridC(below1, right1, top1, :) + ...
                     gridC(   row, right1, bot1, :) + ...
                     gridC(below1,    col, bot1, :) + ...
                     gridC(below1, right1, bot1, :) ; %interlayer
        neighbors2 = gridC(above1,    col,  pil, :) + ...
                     gridC(below1,    col,  pil, :) + ...
                     gridC(   row,  left1,  pil, :) + ...
                     gridC(   row, right1,  pil, :) + ...
                     gridC(above1, right1,  pil, :) + ...
                     gridC(below1,  left1,  pil, :) ; %intralayer
        neighbors3 = zeros(1,1,1,3);
    elseif Lat == "tVCNH"
        neighbors1 = gridC(   row,    col, top1, :) + ...
                     gridC(below1, right1, top1, :) + ...
                     gridC(   row,    col, bot1, :) + ...
                     gridC(below1, right1, bot1, :) ; %inter-nearest
        neighbors2 = gridC(   row, right1, top1, :) + ...
                     gridC(below1,    col, top1, :) + ...
                     gridC(   row, right1, bot1, :) + ...
                     gridC(below1,    col, bot1, :) ; %inter-secnearest
        neighbors3 = gridC(above1,    col,  pil, :) + ...
                     gridC(below1,    col,  pil, :) + ...
                     gridC(   row,  left1,  pil, :) + ...
                     gridC(   row, right1,  pil, :) + ...
                     gridC(above1, right1,  pil, :) + ...
                     gridC(below1,  left1,  pil, :) ; %intra-triagnle
    end
    Ea = - 2 * Sp^2 * sum(gridTC(1,1,1,:)     .* ...
                         (J1 .* neighbors1     + ...
                          J2 .* neighbors2     + ...
                          J3 .* neighbors3))   + ...
         - Sp^2 * D * gridTC(1,1,1,3).^2 ;
    Eb = - 2 * Sp^2 * sum(gridC(row,col,pil,:).* ...
                         (J1 .* neighbors1     + ...
                          J2 .* neighbors2     + ...
                          J3 .* neighbors3))   + ...
         - Sp^2 * D * gridC(row,col,pil,3).^2 ;
    dE = Ea - Eb ;
    % Transition probabilities and performed on the chosen spin
    if dE < 0
    transition = 1;
    else
    transition = (rand() < exp(-dE/(kb*Ts(t))));
    end
    gridC(row,col,pil,:) = gridC(row,col,pil,:) .* (1-transition) + gridTC .* transition;
    % Transform back from Cartisian to Spherecal
    newC = zeros(1,3);
    for in = 1:3
    newC(in) = gridC(row, col, pil, in);
    end
    gridS(row, col, pil, 1) = acos(newC(3));
    gridS(row, col, pil, 2) = acos(newC(1)/(sqrt(newC(1)^2+newC(2)^2)+eps));
    %pick = 1;
    if i == estep
    % Calculate total E
        if Lat == "tVCHH"
            shift1 = circshift(gridC, [ 0  1  1]) + ...
                     circshift(gridC, [ 1  0  1]) + ...
                     circshift(gridC, [ 1  1  1]) + ...
                     circshift(gridC, [ 0  1 -1]) + ...
                     circshift(gridC, [ 1  0 -1]) + ...
                     circshift(gridC, [ 1  1 -1]) ;
            shift2 = circshift(gridC, [ 1  0  0]) + ...
                     circshift(gridC, [-1  0  0]) + ...
                     circshift(gridC, [ 0  1  0]) + ...
                     circshift(gridC, [ 0 -1  0]) + ...
                     circshift(gridC, [-1  1  0]) + ...
                     circshift(gridC, [ 1 -1  0]) ;
            Eini = -2*Sp^2*sum(sum(sum(sum(gridC          .* ...
                                        (J1 * shift1       + ...
                                         J2 * shift2 ))))) + ...
                   -D*Sp^2*sum(sum(sum(gridC(:,:,:,3).^2)));
        elseif Lat == "tVCNH"
            shift1 = circshift(gridC, [ 0  0  1]) + ...
                     circshift(gridC, [ 1  1  1]) + ...
                     circshift(gridC, [ 0  0 -1]) + ...
                     circshift(gridC, [ 1  1 -1]) ;
            shift2 = circshift(gridC, [ 0  1  1]) + ...
                     circshift(gridC, [ 1  0  1]) + ...
                     circshift(gridC, [ 0  1 -1]) + ...
                     circshift(gridC, [ 1  0 -1]) ;
            shift3 = circshift(gridC, [ 1  0  0]) + ...
                     circshift(gridC, [-1  0  0]) + ...
                     circshift(gridC, [ 0  1  0]) + ...
                     circshift(gridC, [ 0 -1  0]) + ...
                     circshift(gridC, [-1  1  0]) + ...
                     circshift(gridC, [ 1 -1  0]) ;
            Eini = -2*Sp^2*sum(sum(sum(sum(gridC             .* ...
                                          (J1 * shift1        + ...
                                           J2 * shift2        + ...
                                           J3 * shift3 )))))  + ...
                   -D*Sp^2*sum(sum(sum(gridC(:,:,:,3).^2)));
        end
    E0 =  Eini;
    end
    
    if i > estep %&& mod(i,pick) == 0  ; % E0: the total energy of step i
        E0 =  E0 + dE * (transition == 1);
        E1 =  E1 + E0        ;
        E2 =  E2 + E0^2      ;
        
        M0 =  2 * Sp * sum(sum(gridC(:,:,3)));
        M1 =  M1 + M0        ;
        M2 =  M2 + M0^2      ;
        M0 =  0.0            ;
    end
    % calculate average E&M per site

    % Display the current state of the system (optional)
    %image((grid+1)*128);
    %%xlabel(sprintf('t = %0.2f, M = %0.2f, E = %0.2f', T, M/L^2, E/L^2));
    %set(gca,'YTickLabel',[],'XTickLabel',[]);
    %axis square; colormap bone; drawnow;
    end
    time2 = toc                    ;
    time1 = time1 + time2          ;
    time3 = (time2 + time3*(t-1))/t;
    % Sum up our variables of interest    
    Ms(t) = abs(M1)/(mstep*L^2);
    Mx(t) = (M2/mstep-(M1/mstep)^2)*const;
    Cs(t) = (E2/mstep-(E1/mstep)^2)*const/Ts(t);
    Es(t) =  E1/(mstep*L^2);
    E1 = 0.0; E2 = 0.0;
    M1 = 0.0; M2 = 0.0;
end
close(bar)
% Count the number of clusters of 'spin up' states
%[L, num] = bwlabel(grid == 1, 4);